// notices 生成根目录的 THIRD_PARTY_NOTICES.md：列出 Windows 版程序里实际用到的开源软件和它们的许可证。
//
// 包括三部分：
//  1. Go 模块：用 `go list -deps` 找出编译 Windows 版时真正链接进 exe 的包，
//     再到 Go 的模块缓存里读每个包最近的 LICENSE 文件（有的模块里某个子目录有自己的许可证，也会单独列出）
//  2. 插件运行时内置的 JS 库：直接用 scripts/jslib/build.mjs 生成的 internal/jsrt/libs/NOTICES.md
//  3. 界面用的字体 Nunito：frontend/src/assets/fonts/OFL.txt
//
// 只用 Go 标准库，不需要联网（模块缓存里没有时 go list 会自动下载）。
// 用法（在项目根目录）：go run ./scripts/notices
package main

import (
	"bufio"
	"bytes"
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
)

// licenseFile 匹配许可证文件名：LICENSE、LICENSE.txt、LICENSE-GO、LICENSE_V8、COPYING、UNLICENSE 等
var licenseFile = regexp.MustCompile(`(?i)^(licen[cs]e|copying|unlicense)([._-].*)?$`)

// module 是一个 Go 模块和它的许可证文件
type module struct {
	Path, Version, Dir string
	Files              []string // 许可证文件的完整路径，按路径排序
}

func main() {
	modules, err := goModules()
	if err != nil {
		log.Fatal(err)
	}
	jsPart, err := os.ReadFile("internal/jsrt/libs/NOTICES.md")
	if err != nil {
		log.Fatalf("读取 JS 库的许可证说明失败（先运行 scripts/jslib 的 npm run build）：%v", err)
	}
	ofl, err := os.ReadFile("frontend/src/assets/fonts/OFL.txt")
	if err != nil {
		log.Fatal(err)
	}

	var b strings.Builder
	b.WriteString(`# 第三方许可证说明（Third-party notices）

极拍 SwiftPaw 本身使用 MIT 许可证，见 [LICENSE](LICENSE)。Windows 版程序里还包含下面这些开源软件，
它们各自的许可证原文附在后面。本文件由 ` + "`go run ./scripts/notices`" + ` 自动生成，请不要手动修改。

SwiftPaw itself is released under the MIT License (see LICENSE). The Windows build also contains the
open-source software listed below; the full license texts follow. This file is generated by
` + "`go run ./scripts/notices`" + `; please don't edit it by hand.

## 汇总

### Go 模块（编译进 SwiftPaw.exe）

| 模块 | 版本 | 许可证 |
|------|------|--------|
`)
	for _, m := range modules {
		fmt.Fprintf(&b, "| %s | %s | %s |\n", m.Path, m.Version, strings.Join(m.licenseTypes(), "、"))
	}
	b.WriteString(`
### 插件运行时内置的 JS 库

见下面的“插件运行时内置的 JS 库”一节。

### 字体

| 字体 | 许可证 |
|------|--------|
| Nunito（界面里的英文和数字） | SIL Open Font License 1.1（OFL.txt） |

---

## Go 模块

`)
	for _, m := range modules {
		fmt.Fprintf(&b, "### %s@%s（%s）\n\n%s\n\n", m.Path, m.Version, strings.Join(m.licenseTypes(), "、"), repoURL(m.Path))
		for _, f := range m.Files {
			rel, _ := filepath.Rel(m.Dir, f)
			text, err := os.ReadFile(f)
			if err != nil {
				log.Fatal(err)
			}
			fmt.Fprintf(&b, "#### %s（%s）\n\n%s\n\n", filepath.ToSlash(rel), classify(string(text)), fence(string(text)))
		}
	}
	b.WriteString("---\n\n")
	b.Write(bytes.TrimSpace(jsPart))
	b.WriteString("\n\n---\n\n## 字体：Nunito（SIL Open Font License 1.1）\n\n")
	b.WriteString("文件在 `frontend/src/assets/fonts/`，许可证原文也随程序一起发布为 OFL.txt。\n\n")
	b.WriteString(fence(string(ofl)) + "\n")

	if err := os.WriteFile("THIRD_PARTY_NOTICES.md", []byte(b.String()), 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("已生成 THIRD_PARTY_NOTICES.md：%d 个 Go 模块\n", len(modules))
}

// goModules 列出编译 Windows 版（和 CI 一样的 tags）时用到的所有第三方模块
func goModules() ([]module, error) {
	cmd := exec.Command("go", "list", "-deps", "-tags", "desktop,production",
		"-f", "{{if not .Standard}}{{with .Module}}{{if not .Main}}{{$.Dir}}\t{{.Path}}\t{{.Version}}\t{{.Dir}}{{end}}{{end}}{{end}}", ".")
	cmd.Env = append(os.Environ(), "GOOS=windows", "GOARCH=amd64")
	cmd.Stderr = os.Stderr
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("go list 失败：%v", err)
	}
	byPath := map[string]*module{}
	sc := bufio.NewScanner(bytes.NewReader(out))
	for sc.Scan() {
		parts := strings.Split(sc.Text(), "\t")
		if len(parts) != 4 {
			continue
		}
		pkgDir, m := parts[0], &module{Path: parts[1], Version: parts[2], Dir: parts[3]}
		if old, ok := byPath[m.Path]; ok {
			m = old
		} else {
			byPath[m.Path] = m
		}
		// 从包所在的文件夹往上找，直到模块根目录，用最近的那个文件夹里的许可证
		files, err := nearestLicenses(pkgDir, m.Dir)
		if err != nil {
			return nil, err
		}
		if len(files) == 0 {
			return nil, fmt.Errorf("%s 里找不到许可证文件，需要手动确认", m.Path)
		}
		for _, f := range files {
			if !slices.Contains(m.Files, f) {
				m.Files = append(m.Files, f)
			}
		}
	}
	list := make([]module, 0, len(byPath))
	for _, m := range byPath {
		sort.Strings(m.Files)
		for _, f := range m.Files {
			text, _ := os.ReadFile(f)
			if classify(string(text)) == "未识别" {
				return nil, fmt.Errorf("认不出 %s 的许可证类型，需要手动确认", f)
			}
		}
		list = append(list, *m)
	}
	sort.Slice(list, func(i, j int) bool { return list[i].Path < list[j].Path })
	return list, nil
}

func nearestLicenses(dir, root string) ([]string, error) {
	for {
		entries, err := os.ReadDir(dir)
		if err != nil {
			return nil, err
		}
		var files []string
		for _, e := range entries {
			// LICENSE-LOGO 之类只说明仓库里 logo 图片的来源，图片不会编译进程序，跳过
			if !e.IsDir() && licenseFile.MatchString(e.Name()) && !strings.Contains(strings.ToUpper(e.Name()), "LOGO") {
				files = append(files, filepath.Join(dir, e.Name()))
			}
		}
		if len(files) > 0 || dir == root || !strings.HasPrefix(dir, root) {
			return files, nil
		}
		dir = filepath.Dir(dir)
	}
}

// licenseTypes 返回模块用到的所有许可证类型（去重）
func (m module) licenseTypes() []string {
	var types []string
	for _, f := range m.Files {
		text, _ := os.ReadFile(f)
		for _, t := range strings.Split(classify(string(text)), " + ") {
			if t != "第三方代码说明" && !slices.Contains(types, t) { // 说明文件不算一种许可证
				types = append(types, t)
			}
		}
	}
	return types
}

// classify 按许可证正文里的关键句子判断类型。认不出来时返回“未识别”，生成会失败，提醒人工检查
func classify(text string) string {
	t := strings.Join(strings.Fields(text), " ") // 把换行和多个空格合成一个空格，方便查找
	var found []string
	has := func(s string) bool { return strings.Contains(t, s) }
	// 一个文件里可能有好几种许可证（比如 modernc.org/libc 的第三方说明），每种都检查一遍
	if has("Apache License") && has("Version 2.0") {
		found = append(found, "Apache-2.0")
	}
	if has("Permission is hereby granted, free of charge") {
		found = append(found, "MIT")
	}
	if has("Redistribution and use in source and binary forms") {
		if has("Neither the name") || has("names of its contributors") || has("name of the copyright holder") {
			found = append(found, "BSD-3-Clause")
		} else {
			found = append(found, "BSD-2-Clause")
		}
	}
	if has("Permission to use, copy, modify, and/or distribute this software for any purpose") {
		found = append(found, "ISC")
	}
	if has("Permission to use, copy, modify, and distribute this software and its documentation for any purpose and without fee") {
		found = append(found, "MIT 类（Lucent）")
	}
	if has("This is free and unencumbered software released into the public domain") {
		found = append(found, "Unlicense")
	}
	if len(found) == 0 {
		// 没有许可证正文、只是列出第三方代码来源的说明文件（比如 modernc.org/libc 的 LICENSE-3RD-PARTY.md）
		if has("third party") || has("third-party") || has("3RD PARTY") {
			return "第三方代码说明"
		}
		return "未识别"
	}
	return strings.Join(found, " + ")
}

// repoURL 根据模块路径给出源代码地址
func repoURL(path string) string {
	switch {
	case strings.HasPrefix(path, "golang.org/x/"):
		return "https://cs.opensource.google/go/x/" + strings.Split(strings.TrimPrefix(path, "golang.org/x/"), "/")[0]
	case strings.HasPrefix(path, "modernc.org/"):
		return "https://gitlab.com/cznic/" + strings.Split(strings.TrimPrefix(path, "modernc.org/"), "/")[0]
	}
	parts := strings.Split(path, "/")
	if len(parts) >= 3 {
		return "https://" + strings.Join(parts[:3], "/")
	}
	return "https://" + path
}

// fence 用代码块包住原文；原文里有 ``` 时用更长的围栏
func fence(text string) string {
	mark := "```"
	for strings.Contains(text, mark) {
		mark += "`"
	}
	return mark + "\n" + strings.TrimSpace(text) + "\n" + mark
}
