// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddToPlaylist(arg1, arg2) {
  return window['go']['main']['App']['AddToPlaylist'](arg1, arg2);
}

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreatePlaylist(arg1) {
  return window['go']['main']['App']['CreatePlaylist'](arg1);
}

export function DeletePlaylist(arg1) {
  return window['go']['main']['App']['DeletePlaylist'](arg1);
}

export function FavoriteKeys() {
  return window['go']['main']['App']['FavoriteKeys']();
}

export function GetLyrics(arg1) {
  return window['go']['main']['App']['GetLyrics'](arg1);
}

export function InstallPluginFromFile() {
  return window['go']['main']['App']['InstallPluginFromFile']();
}

export function InstallPluginFromURL(arg1) {
  return window['go']['main']['App']['InstallPluginFromURL'](arg1);
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function PlayLibrary(arg1) {
  return window['go']['main']['App']['PlayLibrary'](arg1);
}

export function PlaySongs(arg1, arg2) {
  return window['go']['main']['App']['PlaySongs'](arg1, arg2);
}

export function PlaylistSongs(arg1) {
  return window['go']['main']['App']['PlaylistSongs'](arg1);
}

export function Playlists() {
  return window['go']['main']['App']['Playlists']();
}

export function PluginUserVariables(arg1) {
  return window['go']['main']['App']['PluginUserVariables'](arg1);
}

export function Plugins() {
  return window['go']['main']['App']['Plugins']();
}

export function QueueAddNext(arg1) {
  return window['go']['main']['App']['QueueAddNext'](arg1);
}

export function QueueNext(arg1) {
  return window['go']['main']['App']['QueueNext'](arg1);
}

export function QueuePlayAt(arg1) {
  return window['go']['main']['App']['QueuePlayAt'](arg1);
}

export function QueuePrevious() {
  return window['go']['main']['App']['QueuePrevious']();
}

export function QueueRemove(arg1) {
  return window['go']['main']['App']['QueueRemove'](arg1);
}

export function QueueSetMode(arg1) {
  return window['go']['main']['App']['QueueSetMode'](arg1);
}

export function QueueState() {
  return window['go']['main']['App']['QueueState']();
}

export function RecentPlays() {
  return window['go']['main']['App']['RecentPlays']();
}

export function RecordPlay(arg1) {
  return window['go']['main']['App']['RecordPlay'](arg1);
}

export function ReloadPlugins() {
  return window['go']['main']['App']['ReloadPlugins']();
}

export function RemoveBackgroundImage() {
  return window['go']['main']['App']['RemoveBackgroundImage']();
}

export function RemoveFromPlaylist(arg1, arg2) {
  return window['go']['main']['App']['RemoveFromPlaylist'](arg1, arg2);
}

export function RenamePlaylist(arg1, arg2) {
  return window['go']['main']['App']['RenamePlaylist'](arg1, arg2);
}

export function ResolveSong(arg1) {
  return window['go']['main']['App']['ResolveSong'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function ScanMusic(arg1) {
  return window['go']['main']['App']['ScanMusic'](arg1);
}

export function SearchOnline(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchOnline'](arg1, arg2, arg3);
}

export function SelectBackgroundImage() {
  return window['go']['main']['App']['SelectBackgroundImage']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function SetPluginEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetPluginEnabled'](arg1, arg2);
}

export function SetPluginUserVariables(arg1, arg2) {
  return window['go']['main']['App']['SetPluginUserVariables'](arg1, arg2);
}

export function ToggleFavorite(arg1) {
  return window['go']['main']['App']['ToggleFavorite'](arg1);
}

export function UninstallPlugin(arg1) {
  return window['go']['main']['App']['UninstallPlugin'](arg1);
}
