// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {queue} from '../models';
import {music} from '../models';

export function LoadConfig():Promise<main.AppConfig>;

export function PlayLibrary(arg1:number):Promise<queue.State>;

export function QueueAddNext(arg1:music.Song):Promise<queue.State>;

export function QueueNext(arg1:boolean):Promise<queue.State>;

export function QueuePlayAt(arg1:number):Promise<queue.State>;

export function QueuePrevious():Promise<queue.State>;

export function QueueRemove(arg1:number):Promise<queue.State>;

export function QueueSetMode(arg1:string):Promise<queue.State>;

export function QueueState():Promise<queue.State>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function ScanMusic(arg1:string):Promise<Array<music.Song>>;

export function SelectFolder():Promise<string>;
