// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {music} from '../models';
import {store} from '../models';
import {lyrics} from '../models';
import {plugin} from '../models';
import {core} from '../models';
import {queue} from '../models';

export function AddToPlaylist(arg1:number,arg2:music.Song):Promise<number>;

export function AppVersion():Promise<string>;

export function ClearHistory():Promise<void>;

export function CreatePlaylist(arg1:string):Promise<store.Playlist>;

export function DeletePlaylist(arg1:number):Promise<void>;

export function FavoriteKeys():Promise<Array<string>>;

export function GetLyrics(arg1:music.Song):Promise<lyrics.Lyrics>;

export function InstallPluginFromFile():Promise<plugin.Info>;

export function InstallPluginFromURL(arg1:string):Promise<Array<plugin.Info>>;

export function LoadConfig():Promise<core.AppConfig>;

export function PlayLibrary(arg1:number):Promise<queue.State>;

export function PlaySongs(arg1:Array<music.Song>,arg2:number):Promise<queue.State>;

export function PlaylistSongs(arg1:number):Promise<Array<music.Song>>;

export function Playlists():Promise<Array<store.Playlist>>;

export function PluginUserVariables(arg1:string):Promise<Record<string, string>>;

export function Plugins():Promise<Array<plugin.Info>>;

export function QueueAddNext(arg1:music.Song):Promise<queue.State>;

export function QueueNext(arg1:boolean):Promise<queue.State>;

export function QueuePlayAt(arg1:number):Promise<queue.State>;

export function QueuePrevious():Promise<queue.State>;

export function QueueRemove(arg1:number):Promise<queue.State>;

export function QueueSetMode(arg1:string):Promise<queue.State>;

export function QueueState():Promise<queue.State>;

export function RecentPlays():Promise<Array<music.Song>>;

export function RecordPlay(arg1:music.Song):Promise<void>;

export function ReloadPlugins():Promise<Array<plugin.Info>>;

export function RemoveBackgroundImage():Promise<void>;

export function RemoveFromPlaylist(arg1:number,arg2:string):Promise<void>;

export function RenamePlaylist(arg1:number,arg2:string):Promise<void>;

export function ResolveSong(arg1:music.Song):Promise<string>;

export function SaveConfig(arg1:core.AppConfig):Promise<void>;

export function ScanMusic(arg1:string):Promise<Array<music.Song>>;

export function SearchOnline(arg1:string,arg2:string,arg3:number):Promise<plugin.SearchResult>;

export function SelectBackgroundImage():Promise<string>;

export function SelectFolder():Promise<string>;

export function SetPluginEnabled(arg1:string,arg2:boolean):Promise<void>;

export function SetPluginUserVariables(arg1:string,arg2:Record<string, string>):Promise<plugin.Info>;

export function ToggleFavorite(arg1:music.Song):Promise<boolean>;

export function UninstallPlugin(arg1:string):Promise<void>;
