// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.AppConfig>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;

export function ScanMusic(arg1:string):Promise<Array<main.Song>>;

export function SelectFolder():Promise<string>;
